<?php
require_once 'config.php';
require_auth();

/**
 * Change the admin password from inside the admin — no FTP required.
 *
 * Writes a fresh bcrypt hash into admin/config.local.php (the gitignored
 * override that config.php loads before falling back to the shipped default).
 * Safety rails:
 *   - current password must verify first (throttled like the login form)
 *   - the previous config.local.php is backed up (config.local.php.bak.*)
 *   - after writing, the file is read back and the new hash re-verified;
 *     on any mismatch the backup is restored automatically
 * Recovery if the password is ever lost: delete admin/config.local.php via
 * FTP and the shipped default password applies again (see admin/README.md).
 */

define('LOCAL_CONFIG', __DIR__ . '/config.local.php');

$errors  = [];
$success = '';

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    csrf_check();

    $current = (string)($_POST['current_password'] ?? '');
    $new     = (string)($_POST['new_password'] ?? '');
    $confirm = (string)($_POST['confirm_password'] ?? '');

    // Throttle current-password guesses exactly like the login form — an
    // attacker who hijacks a session shouldn't get free brute-force attempts.
    $clientIp = login_throttle_client_ip();
    $failures = login_failure_count($clientIp);
    if ($failures >= 5) {
        sleep(min(8, $failures - 4));
    }

    if (!password_verify($current, ADMIN_PASSWORD_HASH)) {
        login_register_failure($clientIp);
        $errors[] = 'The current password is incorrect.';
    } else {
        login_reset_failures($clientIp);
        if (strlen($new) < 12) {
            $errors[] = 'The new password must be at least 12 characters. A short sentence or 4+ random words works well.';
        } elseif (strlen($new) > 200) {
            $errors[] = 'The new password is too long (200 characters max).';
        } elseif ($new !== $confirm) {
            $errors[] = 'The two new-password fields do not match.';
        } elseif (password_verify($new, ADMIN_PASSWORD_HASH)) {
            $errors[] = 'The new password must be different from the current one.';
        }
    }

    if (empty($errors)) {
        $hash = password_hash($new, PASSWORD_BCRYPT, ['cost' => 12]);
        $defineLine = "define('ADMIN_PASSWORD_HASH', '" . $hash . "');";

        // Preserve any other overrides in config.local.php (e.g.
        // TRUST_PROXY_FORWARDED) — replace only the hash define.
        if (file_exists(LOCAL_CONFIG)) {
            $body = (string)file_get_contents(LOCAL_CONFIG);
            $newBody = preg_replace(
                "/define\\(\\s*'ADMIN_PASSWORD_HASH'\\s*,\\s*'[^']*'\\s*\\)\\s*;/",
                $defineLine,
                $body,
                1,
                $replaced
            );
            if ($newBody === null) { $replaced = 0; $newBody = $body; }
            if (!$replaced) {
                $newBody = rtrim($newBody) . "\n\n// Added by admin/password.php on " . date('Y-m-d H:i:s') . "\n" . $defineLine . "\n";
            }
        } else {
            $newBody = "<?php\n"
                     . "/**\n"
                     . " * IPC Admin — LOCAL password override (gitignored).\n"
                     . " * Generated by admin/password.php on " . date('Y-m-d H:i:s') . ".\n"
                     . " * config.php loads this file first, so the hash below is the one that counts.\n"
                     . " */\n"
                     . $defineLine . "\n";
        }

        // Back up the current file (keep the 3 most recent; *.bak.* is blocked
        // from the web by admin/.htaccess).
        $backupPath = null;
        if (file_exists(LOCAL_CONFIG)) {
            $backupPath = LOCAL_CONFIG . '.bak.' . date('Ymd-His');
            @copy(LOCAL_CONFIG, $backupPath);
            $baks = glob(LOCAL_CONFIG . '.bak.*');
            if ($baks && count($baks) > 3) {
                sort($baks);
                foreach (array_slice($baks, 0, count($baks) - 3) as $old) @unlink($old);
            }
        }

        if (file_put_contents(LOCAL_CONFIG, $newBody, LOCK_EX) === false) {
            $errors[] = 'Could not write admin/config.local.php — check file permissions (the admin/ folder must be writable).';
        } else {
            // Read back and verify the file really contains a working hash for
            // the new password. If anything is off, restore the backup.
            $check = (string)file_get_contents(LOCAL_CONFIG);
            $ok = preg_match("/define\\(\\s*'ADMIN_PASSWORD_HASH'\\s*,\\s*'([^']+)'\\s*\\)\\s*;/", $check, $m)
                  && password_verify($new, $m[1]);
            if (!$ok) {
                if ($backupPath && file_exists($backupPath)) @copy($backupPath, LOCAL_CONFIG);
                $errors[] = 'Verification of the written file failed — the previous password was restored. Nothing changed.';
            } else {
                audit_log('password', 'admin', 'Admin password changed');
                regenerate_session_id();
                $success = 'Password changed. Use the new password the next time you sign in. Store it somewhere safe — if it is ever lost, recovery requires deleting admin/config.local.php over FTP (see admin/README.md).';
            }
        }
    }
}

$navActive = 'password';
?>
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <link rel="icon" type="image/svg+xml" href="logo.svg" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>IPC Admin — Change Password</title>
  <style>
    *, *::before, *::after { box-sizing: border-box; }
    body { font-family: system-ui, sans-serif; background: #f0f4f8; margin: 0; color: #141414; }
    main { max-width: 520px; margin: 0 auto; padding: 40px 24px; }
    h1 { font-size: 22px; font-weight: 800; margin: 0 0 4px; }
    .sub { font-size: 13px; color: #6b7280; margin: 0 0 28px; }
    .card { background: #fff; border: 1px solid #e5e9ee; border-radius: 12px; padding: 28px; margin-bottom: 20px; }
    .form-group { margin-bottom: 18px; }
    label { display: block; font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.08em; color: #6b7280; margin-bottom: 6px; }
    input[type=password] { width: 100%; padding: 11px 14px; border: 1px solid #d1d9e0; border-radius: 8px; font-size: 14px; color: #141414; outline: none; }
    input[type=password]:focus { border-color: #005da3; box-shadow: 0 0 0 3px rgba(0,93,163,0.1); }
    .hint { font-size: 11px; color: #9ca3af; margin-top: 5px; }
    .btn-primary { width: 100%; padding: 12px; background: #005da3; color: #fff; border: none; border-radius: 8px; font-size: 14px; font-weight: 600; cursor: pointer; }
    .btn-primary:hover { background: #004e8c; }
    .error-list { background: #fef2f2; color: #dc2626; border: 1px solid #fecaca; border-radius: 8px; padding: 12px 16px; margin-bottom: 20px; }
    .error-list li { font-size: 13px; margin-bottom: 4px; }
    .alert-success { background: #f0fdf4; color: #166534; border: 1px solid #bbf7d0; border-radius: 8px; padding: 12px 16px; margin-bottom: 20px; font-size: 13px; }
    .note { background: #fffbeb; border: 1px solid #fde68a; color: #92400e; border-radius: 8px; padding: 12px 16px; font-size: 12px; margin-top: 16px; }
  </style>
</head>
<body>
<?php include 'nav.php'; ?>
<main>
  <h1>Change Password</h1>
  <p class="sub">Updates the admin sign-in password. Takes effect on your next sign-in; your current session stays active.</p>

  <?php if (!empty($errors)): ?>
    <ul class="error-list"><?php foreach ($errors as $e): ?><li><?= h($e) ?></li><?php endforeach; ?></ul>
  <?php endif; ?>
  <?php if ($success): ?>
    <div class="alert-success">✅ <?= h($success) ?></div>
  <?php endif; ?>

  <div class="card">
    <form method="POST" autocomplete="off">
      <div class="form-group">
        <label for="current_password">Current password</label>
        <input type="password" id="current_password" name="current_password" autocomplete="current-password" required />
      </div>
      <div class="form-group">
        <label for="new_password">New password</label>
        <input type="password" id="new_password" name="new_password" autocomplete="new-password" minlength="12" required />
        <div class="hint">At least 12 characters. A short sentence or 4+ random words is both strong and memorable.</div>
      </div>
      <div class="form-group">
        <label for="confirm_password">Repeat new password</label>
        <input type="password" id="confirm_password" name="confirm_password" autocomplete="new-password" minlength="12" required />
      </div>
      <input type="hidden" name="csrf_token" value="<?= h(csrf_token()) ?>">
      <button type="submit" class="btn-primary">Change Password →</button>
    </form>
    <div class="note">⚠ Store the new password in a password manager. There is no “forgot password” email — if it's lost, recovery means deleting <code>admin/config.local.php</code> on the server via FTP, which resets to the original password.</div>
  </div>
</main>
</body>
</html>
